version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean test 
  post_build:
    commands:
      - mvn clean package -Dmaven.test.skip=true
