version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean test 
  post_build:
    commands:
      - mvn clean package -Dmaven.test.skip=true
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 959166133864.dkr.ecr.us-east-2.amazonaws.com
      - docker build -t sample_cluster_repo .
      - docker tag sample_cluster_repo:latest 959166133864.dkr.ecr.us-east-2.amazonaws.com/sample_cluster_repo:latest
      - docker push 959166133864.dkr.ecr.us-east-2.amazonaws.com/sample_cluster_repo:latest
artifacts:
  files:
    - '**/*'
  name: s3-to-s3-latest-build.zip
